# .github/workflows/trivy-scan.yml
name: Docker Image Build and Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker Image
        working-directory: projects/Merge/pdfmerger
        run: |
          docker build -t my-app:latest .

      # Pull the Trivy image
      - name: Pull Trivy Scanner
        run: docker pull aquasec/trivy:latest

      # Run Trivy scan on the Docker image
      #- name: Scan Docker Image with Trivy
       # run: |
        #  docker run --rm \
        #    -v /var/run/docker.sock:/var/run/docker.sock \
        #    -v $HOME/.cache/trivy:/root/.cache/trivy \
        #    aquasec/trivy:latest image --exit-code 1 --severity CRITICAL my-app:latest

      - name: Run Trivy in offline mode
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache/trivy:/root/.cache/trivy \
            aquasec/trivy:latest image --skip-update --exit-code 1 --severity CRITICAL my-app:latest

