# .github/workflows/trivy-scan.yml
name: Docker Image Build and Security Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t pdfmerger:latest ./projects/Merge/pdfmerger
          docker build -t pdfsplitter:latest ./projects/Split/pdfsplitter
          docker build -t datetime:latest ./projects/DateTime/src/main/java/org/example
          docker build -t randomnumber:latest ./projects/RandomNo/src/main/java/org/example

      - name: Scan Docker Images with Trivy
        run: |
          images=("pdfmerger" "pdfsplitter" "datetime" "randomnumber")
          scan_results_dir="./trivy-results"
          mkdir -p "$scan_results_dir"
          for image in "${images[@]}"; do
            echo "Scanning Docker Image: $image..."
            trivy_output="$scan_results_dir/${image}_scan_results.txt"
            docker run \
              --rm \
              -v "$(realpath .):/opt/src" \
              -v /run/docker.sock:/var/run/docker.sock \
              -v /tmp/trivy-cache:/cache \
              -e "TRIVY_DB_REPOSITORY=public.ecr.aws/aquasecurity/trivy-db" \
              -e "TRIVY_JAVA_DB_REPOSITORY=public.ecr.aws/aquasecurity/trivy-java-db" \
              -w /opt/src \
              aquasec/trivy:0.56.2 --cache-dir /cache image --quiet $image:latest > "$trivy_output"
          done

      - name: Upload Trivy Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results/

