# .github/workflows/trivy-scan.yml
name: Docker Image Build and Security Scan

on:
  push:
    branches:
      - container_security
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t pdfmerger:latest ./projects/Merge/pdfmerger
          docker build -t pdfsplitter:latest ./projects/Split/pdfsplitter

      - name: Scan Docker Images with Trivy
        run: |
          images=("pdfmerger" "pdfsplitter")
          for image in "${images[@]}"; do
            echo "Scanning Docker Image: $image..."
            docker run \
              --rm \
              -v "$(realpath .):/opt/src" \
              -v /run/docker.sock:/var/run/docker.sock \
              -v /tmp/trivy-cache:/cache \
              -e "TRIVY_DB_REPOSITORY=public.ecr.aws/aquasecurity/trivy-db" \
              -e "TRIVY_JAVA_DB_REPOSITORY=public.ecr.aws/aquasecurity/trivy-java-db" \
              -w /opt/src \
              aquasec/trivy:0.56.2 --cache-dir /cache image --quiet $image:latest \
              | tee trivy-scan-$image-results.txt
          done
          
      - name: Upload Trivy Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-results
          path: trivy-results/

