name: Dependency Check

on:
  push:
    branches:
      - main
      - PackageScanner
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  
          java-version: '11'
      - name: Run OWASP Dependency Check
        uses: xvik/gradle-dependency-check-action@v1.4.1
        with:
          arguments: "--scan ./ --format HTML --out ./dependency-check-report.html"
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: ./dependency-check-report.html
