name: Dependency Check

on:
  push:
    branches:
      - main
      - PackageScanner
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download OWASP Dependency Check
        run: |
          echo "Downloading OWASP Dependency Check..."
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
          echo "Unzipping the file..."
          unzip -o dependency-check-8.1.2-release.zip -d $HOME/dependency-check
          echo "Listing the contents of the dependency-check directory:"
          ls -R $HOME/dependency-check
          echo "Done."
      - name: Verify existence of dependency-check.sh
        run: |
          echo "Checking if dependency-check.sh exists..."
          if [ -f "$HOME/dependency-check/bin/dependency-check.sh" ]; then
              echo "dependency-check.sh found."
          else
              echo "dependency-check.sh NOT found."
              exit 1
          fi
      - name: Make dependency-check.sh executable
        run: |
          echo "Attempting to set permissions for dependency-check.sh"
          chmod +x $HOME/dependency-check/bin/dependency-check.sh
          echo "Permissions set."
      - name: Run OWASP Dependency Check
        run: |
          echo "Running OWASP Dependency Check..."
          $HOME/dependency-check/bin/dependency-check.sh --project JavaApp --scan ./ --format HTML --out ./dependency-check-report.html
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check-Report
          path: ./dependency-check-report.html
