name: Dependency Check

on:
  push:
    branches:
      - main
      - PackageScanner
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run OWASP Dependency Check
        run: |
            curl -LO https://github.com/jeremylong/DependencyCheck/releases/tag/v11.0.0/dependency-check-11.0.0-release.zip 
            unzip dependency-check-11.0.0-release.zip  -d $HOME/dependency-check
            $HOME/dependency-check/bin/dependency-check.sh --project JavaApp --scan ./ --format HTML --out ./dependency-check-report.html
      - name: Run OWASP Dependency Check
        run: |
            $HOME/dependency-check/bin/dependency-check.sh --project JavaApp --scan ./ --format HTML --out ./dependency-check-report.html
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check-Report
          path: ./dependency-check-report.html