name: Dependency Check

on:
  push:
    branches:
      - main
      - package_scanner
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download OWASP Dependency Check
        run: |
          echo "Downloading OWASP Dependency Check version 11.0.0..."
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v11.0.0/dependency-check-11.0.0-release.zip
          if [ -f "dependency-check.zip" ]; then
            echo "Download successful. Verifying file type..."
            file dependency-check.zip
          else
            echo "Download failed: dependency-check.zip does not exist."
            exit 1
          fi
        
          echo "Unzipping the file..."
          unzip -o dependency-check.zip -d $HOME/dependency-check
          echo "Listing the contents of the dependency-check directory after unzipping:"
          ls -R $HOME/dependency-check  # Überprüfen des Inhalts nach dem Entpacken
      - name: Verify existence of dependency-check.sh
        run: |
          echo "Checking if dependency-check.sh exists..."
          find $HOME/dependency-check -name "dependency-check.sh"
      - name: Make dependency-check.sh executable
        run: |
          echo "Attempting to set permissions for dependency-check.sh"
          chmod +x $(find $HOME/dependency-check -name "dependency-check.sh") || echo "dependency-check.sh not found, skipping chmod."
      - name: Run OWASP Dependency Check
        env:
          NVD_API_KEY: ${{ '698c222e-b345-47e0-a4ed-b4d039e8a408' }}  # Hier wird der API-Schlüssel verwendet
        run: |
          echo "Running OWASP Dependency Check..."
          $(find $HOME/dependency-check -name "dependency-check.sh") --project JavaApp --scan ./ --format HTML --out ./dependency-check-report.html
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check-Report
          path: ./dependency-check-report.html